# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022

steps:
- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'InitManage/InitManage.sln'
    arguments: '-c Release -f net6.0-android'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*-Signed.aab'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

#Your build pipeline references an undefined variable named ‘Parameters.appFiles’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

- task: AppCenterDistribute@2
  displayName: 'Deploy $(build.binariesdirectory)/$(BuildConfiguration)/*.aab to Visual Studio App Center'
  inputs:
    serverEndpoint: AppCenter
    appSlug: 'https://appcenter.ms/users/thomas.bernard-diiage.org/apps/IN-IT-Manage'
    appFile: '$(Parameters.appFiles)'
    symbolsIncludeParentDirectory: false
    releaseNotesInput: 'New release'
  condition: succeededOrFailed()